import { Control } from "./Control";
import "./globals.css";
import Link from "next/link";
import { myServerClient } from "../../utils/supabase/server";

export const revalidate = 0;

export const metadata = {
  title: "WEB tutorial",
  description: "Generated by KIDOHU",
};

export default async function RootLayout({ children }) {
  const supabase = myServerClient();
  let { data: page, error } = await supabase.from('page').select('*');

  return (
    <html>
      <body>
        <h1><Link href="/">공감</Link></h1>
        <ol>
          {page.map(p => 
            <li key={p.id}>
              <Link href={`/read/${p.id}`}>{p.title}</Link>
            </li>
          )}
        </ol>
          {children}
          <Control />
      </body>
    </html>
  );
}
